name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: proc
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          debug: yes
          token: ${{ secrets.MATRICS_TOKEN }}

          user: tbjuechen
          template: classic
          base: header, activity, community, repositories, metadata
          # config_display: columns
          config_timezone: Asia/Shanghai
          plugin_calendar: yes
          plugin_calendar_limit: 1
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_traffic: yes
          # 开启音乐插件
          plugin_music: yes
          # 设置为 playlist 模式（必须，因为 Apple Music 仅支持此模式）
          plugin_music_provider: apple 
          # 填入你刚才复制的 Embed URL
          plugin_music_playlist: https://embed.music.apple.com/cn/playlist/%E8%BD%A6%E8%BD%BD/pl.u-RRbVvlxIDLbaAm       
          # 限制显示的歌曲数量
          plugin_music_limit: 4
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, languages, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: "0"